# -*- coding: utf-8 -*-
"""
DMGSO Reviewer-Driven Sensing-Topology Full Experiment (Crash-Safe)
===================================================================

Purpose
-------
This revision-only experiment addresses the reviewer request to investigate
the number and topology of deterministic sensing directions, especially at
D = 20 and D = 40.

IMPORTANT:
- The historical DMGSO implementation is NOT modified on disk.
- Historical DMGSO results are NOT rerun here because complete frozen results
  already exist for D = 20 and D = 40 under the original topology.
- This runner generates ONLY the three new controlled topology variants:
      AXIS_ONLY
      FIXED8_UNIQUE
      DIM_ADAPTIVE
- Final analysis must combine these new results with the frozen historical
  DMGSO results.

Experimental protocol
---------------------
COCO/BBOB:
    24 functions
    15 instances: 1-5 and 71-80
    dimensions: D = 20, 40
    run_id: 0, 1, 2, 3, 4
    FE_budget = 1000 * D

New runs:
    3 topologies * 24 functions * 15 instances * 2 dimensions * 5 run_ids
    = 10,800 runs

Historical topology
-------------------
The manuscript implementation uses:
    K = 2D + 8 stored directions

The original parity-based diagonal construction stores 8 diagonal directions
but yields only 2 unique diagonal patterns. Historical results are preserved
exactly as previously generated and are not overwritten or silently corrected.

Revision-only controlled topologies
-----------------------------------
AXIS_ONLY
    2D axis-aligned directions only.

FIXED8_UNIQUE
    2D axis directions + 8 deterministic unique dense sign-pattern directions.
    This keeps the same stored-direction count and normal per-iteration FE cost
    as the historical topology while removing diagonal duplication.

DIM_ADAPTIVE
    2D axis directions + D deterministic unique dense sign-pattern directions.
    This tests increased directional coverage whose cost scales with dimension.

The unique dense sign patterns are deterministic and generated by a Gray-code
construction. No stochastic sampling is introduced.

Crash-safe behavior
-------------------
- One CSV row is appended immediately after every completed run.
- Every row is flushed and fsynced.
- On restart, existing complete experiment keys are detected and skipped.
- Duplicate keys are refused.
- The runner never overwrites historical source data.
- The output file may be resumed safely after interruption.

Corrected BBOB error
--------------------
For every new run:
    error_corrected = best_f - f_opt_official

The official f* values are read from the frozen revision reference file.

Output
------
sensing_topology/raw/
    topology_full_run_summary_revision.csv

sensing_topology/logs/
    topology_full_run_audit_revision.txt

After all 10,800 rows are complete, a strict final audit is performed.
"""

from __future__ import annotations

import csv
import hashlib
import os
import sys
import time
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

# =============================================================================
# 1. PATHS
# =============================================================================

PROJECT = Path("/mnt/d/PHD/MIDO-GS/DMGSO_Project/KSB_DMGSO")
REVISION = Path("/mnt/d/PHD/DMGSO_Information Scince/Revision")

OUT_BASE = REVISION / "sensing_topology"
RAW_DIR = OUT_BASE / "raw"
LOG_DIR = OUT_BASE / "logs"

OUT_CSV = RAW_DIR / "topology_full_run_summary_revision.csv"
AUDIT_TXT = LOG_DIR / "topology_full_run_audit_revision.txt"

FOPT_PATH = (
    REVISION
    / "coco_bbob"
    / "backup"
    / "frozen_20260911"
    / "bbob_fopt_cocoex_2.8.2_FROZEN.csv"
)

EXPECTED_FOPT_SHA256 = (
    "ff273dc9c7cd97c15f3abf70e7b0816ca76137b57cc7907fb7aea814357b5dc0"
)

sys.path.insert(0, str(PROJECT))

import core.dmgso_core as dmgso_core
from core.dmgso_core import DMGSOConfig, dmgso_optimize

try:
    import cocoex
except ImportError as exc:
    raise ImportError(
        "cocoex is required in the revision Python environment."
    ) from exc


# =============================================================================
# 2. FROZEN EXPERIMENT DESIGN
# =============================================================================

TOPOLOGIES = [
    "AXIS_ONLY",
    "FIXED8_UNIQUE",
    "DIM_ADAPTIVE",
]

DIMENSIONS = {20, 40}
FUNCTIONS = set(range(1, 25))
INSTANCES = {
    1, 2, 3, 4, 5,
    71, 72, 73, 74, 75,
    76, 77, 78, 79, 80,
}
RUN_IDS = list(range(5))
BUDGET_MULT = 1000

EXPECTED_ROWS = (
    len(TOPOLOGIES)
    * len(DIMENSIONS)
    * len(FUNCTIONS)
    * len(INSTANCES)
    * len(RUN_IDS)
)  # 10,800

ERROR_TOL = 1e-8

KEY = [
    "topology",
    "function_id",
    "instance_id",
    "dimension",
    "run_id",
]

FIELDNAMES = [
    "suite",
    "topology",
    "function_id",
    "instance_id",
    "dimension",
    "run_id",
    "FE_budget",
    "budget_mult",
    "fe_used",
    "best_f",
    "f_opt_official",
    "error_corrected",
    "n_accept",
    "n_reloc",
    "wall_time_sec",
    "stored_directions",
    "unique_directions",
    "duplicate_directions",
    "normal_iteration_fe",
    "status",
]


# =============================================================================
# 3. PROVENANCE UTILITIES
# =============================================================================

def sha256_file(path: Path) -> str:
    """Return SHA-256 of a file without modifying it."""
    h = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def verify_fopt_reference() -> None:
    """Verify the frozen official f* reference before any run starts."""
    if not FOPT_PATH.exists():
        raise FileNotFoundError(
            f"Frozen official f* file not found:\n{FOPT_PATH}"
        )

    actual = sha256_file(FOPT_PATH)

    if actual != EXPECTED_FOPT_SHA256:
        raise RuntimeError(
            "Frozen official f* SHA-256 mismatch.\n"
            f"Expected: {EXPECTED_FOPT_SHA256}\n"
            f"Actual:   {actual}"
        )


# =============================================================================
# 4. REVISION-ONLY DIRECTION TOPOLOGIES
# =============================================================================

def _canonical_key(v: np.ndarray) -> Tuple[int, ...]:
    """Canonicalize a dense ±1 sign vector up to global sign."""
    s = np.where(v >= 0.0, 1, -1).astype(int)

    if s[0] < 0:
        s = -s

    return tuple(int(x) for x in s)


def _gray_code_sign_patterns(D: int, k: int) -> np.ndarray:
    """
    Construct k deterministic unique dense ±1 directions.

    Global sign complements are treated as the same sign-pattern family during
    construction, preventing trivial opposite duplicates from consuming the
    requested diagonal diversity.
    """
    if k <= 0:
        return np.empty((0, D), dtype=np.float64)

    patterns: List[np.ndarray] = []
    seen = set()

    candidate = 1
    max_candidates = max(10000, 1000 * k)

    while len(patterns) < k and candidate <= max_candidates:
        gray = candidate ^ (candidate >> 1)

        v = np.ones(D, dtype=np.float64)

        nbits = max(
            2,
            int(np.ceil(np.log2(D + k + 2))),
        )

        for j in range(D):
            bit_index = (j + candidate) % nbits
            bit = (gray >> bit_index) & 1

            if bit:
                v[j] = -1.0

        # A dense diagonal must contain both signs.
        if np.all(v > 0.0) or np.all(v < 0.0):
            candidate += 1
            continue

        key = _canonical_key(v)

        if key not in seen:
            seen.add(key)
            patterns.append(v)

        candidate += 1

    if len(patterns) != k:
        raise RuntimeError(
            f"Could not construct {k} unique deterministic "
            f"diagonal patterns for D={D}."
        )

    arr = np.vstack(patterns).astype(np.float64)
    arr /= np.linalg.norm(arr, axis=1, keepdims=True)

    return arr


def build_revision_directions(D: int, mode: str) -> np.ndarray:
    """Build one controlled revision topology."""
    I = np.eye(D, dtype=np.float64)

    axes = np.vstack(
        [
            direction
            for j in range(D)
            for direction in (I[j], -I[j])
        ]
    )

    if mode == "AXIS_ONLY":
        return axes

    if mode == "FIXED8_UNIQUE":
        diagonals = _gray_code_sign_patterns(D, 8)
        return np.vstack([axes, diagonals])

    if mode == "DIM_ADAPTIVE":
        diagonals = _gray_code_sign_patterns(D, D)
        return np.vstack([axes, diagonals])

    raise ValueError(
        f"Unknown revision topology: {mode}"
    )


def direction_audit(D: int, mode: str) -> Dict[str, int]:
    """Return direction-count and nominal full-iteration FE accounting."""
    dirs = build_revision_directions(D, mode)

    rounded = np.round(
        dirs,
        decimals=14,
    )

    unique = np.unique(
        rounded,
        axis=0,
    )

    stored = int(len(dirs))
    unique_count = int(len(unique))
    duplicates = stored - unique_count

    return {
        "stored_directions": stored,
        "unique_directions": unique_count,
        "duplicate_directions": duplicates,
        "normal_iteration_fe": 2 * stored + 1,
    }


def validate_topology_design() -> None:
    """Fail fast if the frozen revision topology design has changed."""
    expected = {
        (20, "AXIS_ONLY"): (40, 40, 0, 81),
        (20, "FIXED8_UNIQUE"): (48, 48, 0, 97),
        (20, "DIM_ADAPTIVE"): (60, 60, 0, 121),
        (40, "AXIS_ONLY"): (80, 80, 0, 161),
        (40, "FIXED8_UNIQUE"): (88, 88, 0, 177),
        (40, "DIM_ADAPTIVE"): (120, 120, 0, 241),
    }

    for (D, mode), target in expected.items():
        audit = direction_audit(D, mode)

        observed = (
            audit["stored_directions"],
            audit["unique_directions"],
            audit["duplicate_directions"],
            audit["normal_iteration_fe"],
        )

        if observed != target:
            raise RuntimeError(
                f"Topology design mismatch for D={D}, {mode}.\n"
                f"Expected: {target}\n"
                f"Observed: {observed}"
            )


# =============================================================================
# 5. OFFICIAL f* LOOKUP
# =============================================================================

def load_fopt_lookup() -> Dict[Tuple[int, int, int], float]:
    """Load frozen official BBOB optima into a strict lookup table."""
    df = pd.read_csv(FOPT_PATH)

    required = {
        "function_id",
        "instance_id",
        "dimension",
        "f_opt",
    }

    missing = required - set(df.columns)

    if missing:
        raise RuntimeError(
            f"Frozen f* reference missing columns: {sorted(missing)}"
        )

    key_cols = [
        "function_id",
        "instance_id",
        "dimension",
    ]

    if df.duplicated(key_cols).any():
        raise RuntimeError(
            "Duplicate keys detected in frozen official f* reference."
        )

    lookup = {
        (
            int(row.function_id),
            int(row.instance_id),
            int(row.dimension),
        ): float(row.f_opt)
        for row in df.itertuples(index=False)
    }

    expected_keys = {
        (fid, iid, D)
        for fid in FUNCTIONS
        for iid in INSTANCES
        for D in DIMENSIONS
    }

    missing_keys = expected_keys - set(lookup)

    if missing_keys:
        raise RuntimeError(
            f"Frozen f* reference is missing {len(missing_keys)} required keys."
        )

    return lookup


# =============================================================================
# 6. CRASH-SAFE CSV STATE
# =============================================================================

def read_existing_keys() -> set:
    """
    Validate an existing partial output and return its complete experiment keys.

    The output is append-only. Any duplicate key causes an immediate stop.
    """
    if not OUT_CSV.exists():
        return set()

    df = pd.read_csv(OUT_CSV)

    missing = set(FIELDNAMES) - set(df.columns)

    if missing:
        raise RuntimeError(
            f"Existing output is missing required columns: {sorted(missing)}"
        )

    if df.duplicated(KEY).any():
        duplicated = int(df.duplicated(KEY).sum())
        raise RuntimeError(
            f"Existing output contains {duplicated} duplicate experiment keys."
        )

    if len(df) > EXPECTED_ROWS:
        raise RuntimeError(
            f"Existing output has {len(df)} rows, exceeding expected "
            f"{EXPECTED_ROWS}."
        )

    bad_topology = set(df["topology"].astype(str)) - set(TOPOLOGIES)

    if bad_topology:
        raise RuntimeError(
            f"Unexpected topologies in existing output: {sorted(bad_topology)}"
        )

    if (
        pd.to_numeric(df["fe_used"])
        > pd.to_numeric(df["FE_budget"])
    ).any():
        raise RuntimeError(
            "Existing output contains an FE-budget violation."
        )

    if not (
        df["status"].astype(str).str.lower() == "ok"
    ).all():
        raise RuntimeError(
            "Existing output contains non-ok rows."
        )

    corrected = pd.to_numeric(
        df["error_corrected"],
        errors="coerce",
    ).to_numpy(dtype=float)

    if not np.isfinite(corrected).all():
        raise RuntimeError(
            "Existing output contains non-finite corrected errors."
        )

    if (corrected < -ERROR_TOL).any():
        raise RuntimeError(
            "Existing output contains materially negative corrected errors."
        )

    return {
        (
            str(row.topology),
            int(row.function_id),
            int(row.instance_id),
            int(row.dimension),
            int(row.run_id),
        )
        for row in df.itertuples(index=False)
    }


def append_row_crash_safe(row: Dict) -> None:
    """
    Append one completed run and force it to disk immediately.
    """
    file_exists = OUT_CSV.exists()

    with OUT_CSV.open(
        "a",
        newline="",
        encoding="utf-8",
    ) as stream:
        writer = csv.DictWriter(
            stream,
            fieldnames=FIELDNAMES,
        )

        if not file_exists:
            writer.writeheader()

        writer.writerow(row)

        stream.flush()
        os.fsync(stream.fileno())


# =============================================================================
# 7. ONE CONTROLLED DMGSO RUN
# =============================================================================

def make_objective(problem):
    """Return the COCO objective as a plain deterministic callable."""
    return lambda x: float(problem(x))


def run_one(
    problem,
    topology: str,
    run_id: int,
    fopt_lookup: Dict[Tuple[int, int, int], float],
) -> Dict:
    """
    Run one revision topology while patching only build_directions in memory.
    """
    D = int(problem.dimension)
    fid = int(problem.id_function)
    iid = int(problem.id_instance)

    budget = int(BUDGET_MULT * D)

    lb = np.asarray(
        problem.lower_bounds,
        dtype=np.float64,
    )

    ub = np.asarray(
        problem.upper_bounds,
        dtype=np.float64,
    )

    original_builder = dmgso_core.build_directions

    def patched_build_directions(
        D_in: int,
        k_diag: int = 8,
    ) -> np.ndarray:
        # k_diag is intentionally ignored here. The topology definition is
        # frozen by the revision experiment, while all other core logic remains
        # unchanged.
        return build_revision_directions(
            D_in,
            topology,
        )

    dmgso_core.build_directions = patched_build_directions

    try:
        cfg = DMGSOConfig(
            version="V4",
            D=D,
            FE_budget=budget,
            trace_enable=False,
            refine_enable=False,
        )

        t0 = time.perf_counter()

        result = dmgso_optimize(
            f=make_objective(problem),
            lb=lb,
            ub=ub,
            cfg=cfg,
            run_id=run_id,
        )

        wall = time.perf_counter() - t0

    finally:
        dmgso_core.build_directions = original_builder

    f_opt = float(
        fopt_lookup[(fid, iid, D)]
    )

    best_f = float(result.best_f)
    error_corrected = best_f - f_opt

    if not np.isfinite(best_f):
        raise RuntimeError(
            f"Non-finite best_f for {topology}, F{fid}, I{iid}, D={D}, run={run_id}."
        )

    if not np.isfinite(error_corrected):
        raise RuntimeError(
            "Non-finite corrected error."
        )

    if error_corrected < -ERROR_TOL:
        raise RuntimeError(
            f"Materially negative corrected error: {error_corrected}"
        )

    fe_used = int(result.fe_used)

    if fe_used > budget:
        raise RuntimeError(
            f"FE-budget violation: used {fe_used}, budget {budget}."
        )

    topology_info = direction_audit(
        D,
        topology,
    )

    return {
        "suite": "COCO/BBOB",
        "topology": topology,
        "function_id": fid,
        "instance_id": iid,
        "dimension": D,
        "run_id": int(run_id),
        "FE_budget": budget,
        "budget_mult": BUDGET_MULT,
        "fe_used": fe_used,
        "best_f": best_f,
        "f_opt_official": f_opt,
        "error_corrected": float(error_corrected),
        "n_accept": int(result.n_accept),
        "n_reloc": int(result.n_reloc),
        "wall_time_sec": float(wall),
        **topology_info,
        "status": "ok",
    }


# =============================================================================
# 8. FINAL AUDIT
# =============================================================================

def final_audit() -> pd.DataFrame:
    """Perform a strict audit of the completed 10,800-row dataset."""
    if not OUT_CSV.exists():
        raise RuntimeError(
            "Full topology output file does not exist."
        )

    df = pd.read_csv(OUT_CSV)

    checks = []

    checks.append(
        ("Rows", len(df), EXPECTED_ROWS, len(df) == EXPECTED_ROWS)
    )

    checks.append(
        (
            "Topologies",
            df["topology"].nunique(),
            len(TOPOLOGIES),
            set(df["topology"]) == set(TOPOLOGIES),
        )
    )

    checks.append(
        (
            "Functions",
            df["function_id"].nunique(),
            24,
            set(df["function_id"].astype(int)) == FUNCTIONS,
        )
    )

    checks.append(
        (
            "Instances",
            df["instance_id"].nunique(),
            15,
            set(df["instance_id"].astype(int)) == INSTANCES,
        )
    )

    checks.append(
        (
            "Dimensions",
            sorted(df["dimension"].astype(int).unique().tolist()),
            [20, 40],
            set(df["dimension"].astype(int)) == DIMENSIONS,
        )
    )

    checks.append(
        (
            "Run IDs",
            sorted(df["run_id"].astype(int).unique().tolist()),
            RUN_IDS,
            set(df["run_id"].astype(int)) == set(RUN_IDS),
        )
    )

    duplicate_count = int(
        df.duplicated(KEY).sum()
    )

    checks.append(
        (
            "Duplicate keys",
            duplicate_count,
            0,
            duplicate_count == 0,
        )
    )

    status_bad = int(
        (df["status"].astype(str).str.lower() != "ok").sum()
    )

    checks.append(
        (
            "Non-ok rows",
            status_bad,
            0,
            status_bad == 0,
        )
    )

    budget_bad = int(
        (
            pd.to_numeric(df["fe_used"])
            > pd.to_numeric(df["FE_budget"])
        ).sum()
    )

    checks.append(
        (
            "FE-budget violations",
            budget_bad,
            0,
            budget_bad == 0,
        )
    )

    err = pd.to_numeric(
        df["error_corrected"],
        errors="coerce",
    ).to_numpy(dtype=float)

    nonfinite = int(
        (~np.isfinite(err)).sum()
    )

    negative = int(
        (err < -ERROR_TOL).sum()
    )

    checks.append(
        (
            "Non-finite corrected errors",
            nonfinite,
            0,
            nonfinite == 0,
        )
    )

    checks.append(
        (
            "Material negative corrected errors",
            negative,
            0,
            negative == 0,
        )
    )

    # Every topology × function × instance × dimension block must contain 5 runs.
    blocks = (
        df.groupby(
            [
                "topology",
                "function_id",
                "instance_id",
                "dimension",
            ],
            observed=True,
        )["run_id"]
        .nunique()
    )

    incomplete = int(
        (blocks != 5).sum()
    )

    checks.append(
        (
            "Incomplete 5-run blocks",
            incomplete,
            0,
            incomplete == 0,
        )
    )

    # Verify frozen topology counts row-by-row.
    topology_count_bad = 0

    for row in df.itertuples(index=False):
        expected = direction_audit(
            int(row.dimension),
            str(row.topology),
        )

        observed = (
            int(row.stored_directions),
            int(row.unique_directions),
            int(row.duplicate_directions),
            int(row.normal_iteration_fe),
        )

        target = (
            expected["stored_directions"],
            expected["unique_directions"],
            expected["duplicate_directions"],
            expected["normal_iteration_fe"],
        )

        if observed != target:
            topology_count_bad += 1

    checks.append(
        (
            "Topology-count mismatches",
            topology_count_bad,
            0,
            topology_count_bad == 0,
        )
    )

    passed = all(
        check[3]
        for check in checks
    )

    lines = [
        "DMGSO SENSING-TOPOLOGY FULL RUN — FINAL AUDIT",
        "=" * 72,
        "",
        f"Dataset: {OUT_CSV}",
        f"SHA-256: {sha256_file(OUT_CSV)}",
        "",
    ]

    for label, observed, expected, ok in checks:
        lines.append(
            f"[{'PASS' if ok else 'FAIL'}] "
            f"{label}: {observed} / expected {expected}"
        )

    lines.extend(
        [
            "",
            "Rows by topology:",
            df.groupby("topology").size().to_string(),
            "",
            "Rows by topology/dimension:",
            df.groupby(["topology", "dimension"]).size().to_string(),
            "",
            (
                "FINAL STATUS: FULL TOPOLOGY AUDIT PASSED"
                if passed
                else "FINAL STATUS: FULL TOPOLOGY AUDIT FAILED"
            ),
            "",
        ]
    )

    AUDIT_TXT.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    print()
    print("\n".join(lines))

    if not passed:
        raise RuntimeError(
            "Final full topology audit failed."
        )

    return df


# =============================================================================
# 9. MAIN CRASH-SAFE WORKFLOW
# =============================================================================

def main() -> None:
    print("=" * 88)
    print("DMGSO SENSING-TOPOLOGY FULL RUN — CRASH-SAFE REVISION EXPERIMENT")
    print("=" * 88)

    RAW_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    LOG_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    verify_fopt_reference()
    validate_topology_design()

    print("[PASS] Frozen official f* SHA-256 verified.")
    print("[PASS] Revision topology design verified.")

    fopt_lookup = load_fopt_lookup()
    completed = read_existing_keys()

    print(
        f"[INFO] Existing complete rows: {len(completed)} / {EXPECTED_ROWS}"
    )

    if len(completed) == EXPECTED_ROWS:
        print("[INFO] Dataset is already complete. Running final audit only.")
        final_audit()
        return

    suite = cocoex.Suite(
        "bbob",
        "",
        "",
    )

    completed_now = len(completed)

    # Iterate the suite once. Each problem is used immediately and is not
    # retained after the suite advances, avoiding stale cocoex handles.
    for problem in suite:
        D = int(problem.dimension)

        if D not in DIMENSIONS:
            continue

        fid = int(problem.id_function)
        iid = int(problem.id_instance)

        if fid not in FUNCTIONS:
            continue

        if iid not in INSTANCES:
            continue

        for topology in TOPOLOGIES:
            for run_id in RUN_IDS:
                key = (
                    topology,
                    fid,
                    iid,
                    D,
                    run_id,
                )

                if key in completed:
                    continue

                row = run_one(
                    problem=problem,
                    topology=topology,
                    run_id=run_id,
                    fopt_lookup=fopt_lookup,
                )

                append_row_crash_safe(
                    row
                )

                completed.add(
                    key
                )

                completed_now += 1

                print(
                    f"[{completed_now:05d}/{EXPECTED_ROWS:05d}] "
                    f"{topology:14s} "
                    f"F{fid:02d} "
                    f"I{iid:02d} "
                    f"D={D:02d} "
                    f"run={run_id} "
                    f"FE={row['fe_used']:6d} "
                    f"err={row['error_corrected']:.8e} "
                    f"accept={row['n_accept']} "
                    f"reloc={row['n_reloc']}"
                )

    if len(completed) != EXPECTED_ROWS:
        raise RuntimeError(
            f"Suite traversal ended with {len(completed)} complete rows; "
            f"expected {EXPECTED_ROWS}."
        )

    final_audit()

    print()
    print(
        "[PASS] Reviewer-driven full sensing-topology experiment "
        "completed successfully."
    )
    print("=" * 88)


if __name__ == "__main__":
    main()
