# -*- coding: utf-8 -*-
"""
Crash-Safe CEC2014 Ablation Runner for the Information Sciences Revision
=======================================================================

Scientific purpose
------------------
This script executes the controlled CEC2014 ablation study for the DMGSO
revision while preserving the already-frozen scientific implementation.

The ablation compares five deterministic algorithmic configurations:

    V0 : Pure directional sensing
    V1 : V0 + adaptive step regulation
    V2 : V1 + long-range sensing
    V3 : V2 + memory fusion
    V4 : Full DMGSO, including relocation and policy-like gating

The scientific objective of this experiment is not to introduce new
algorithmic behavior, but to quantify the incremental contribution of the
predefined DMGSO components under matched deterministic configurations.

Revision protocol
-----------------
Main experimental settings:

    Benchmark suite          : CEC2014
    Functions                : F1-F30
    Dimension                : D = 30
    Deterministic configs    : run_id = 0,...,9
    Variants                 : V0-V4
    Maximum FE budget        : 300,000 evaluations per configuration
    Refinement phase         : disabled
    Trace recording          : disabled in the main run

This yields:

    30 functions × 10 deterministic configurations × 5 variants
    = 1,500 run-level records.

Important interpretation of "run_id"
------------------------------------
DMGSO is deterministic. Therefore, run_id does NOT denote an independent
stochastic realization. Instead, it indexes a deterministic initial/configuration
state generated by the frozen implementation.

The same run_id is used across V0-V4 for a given benchmark function. This
preserves a paired experimental design: differences among variants are evaluated
under matched deterministic configurations rather than unrelated starts.

Scientific implementation freeze
---------------------------------
This file is intentionally only an execution-safety wrapper. It imports and uses
the frozen revision implementation from:

    run_ablation_dmgso_cec2014_revision.py
    dmgso_core_revision.py
    wrapper_cec2014_revision.py

It MUST NOT redefine, alter, or tune:
    - DMGSO equations,
    - component definitions,
    - benchmark functions,
    - CEC2014 optimum values,
    - FE budgets,
    - deterministic initialization logic,
    - version semantics,
    - stopping rules.

No function-specific or benchmark-specific parameter tuning is performed here.

Why this safety wrapper exists
------------------------------
Long benchmark runs can be interrupted by operating-system restarts, power loss,
terminal closure, or manual interruption. The original frozen runner protects
against accidental overwrite, but it is not resume-aware.

This wrapper therefore provides execution safety without changing the science:

    1. Existing valid results are never deleted or rewritten.
    2. Completed records are detected from their unique experimental key.
    3. Only missing records are executed.
    4. Every completed result is appended immediately to disk.
    5. Duplicate rows are rejected.
    6. Existing data are audited before continuation.
    7. FE-budget, numerical-integrity, and benchmark-error checks are enforced.
    8. A final completeness audit requires exactly 1,500 unique records.
    9. Dry-run is the default; computation requires the explicit --execute flag.

Restart behavior
----------------
If execution is interrupted, rerunning this script with --execute will:

    - read the existing CSV,
    - validate all completed rows,
    - identify the remaining experimental combinations,
    - skip completed combinations,
    - continue from the next missing record.

Thus, previously completed optimization results are preserved exactly as written.

Raw-data policy
---------------
The run-level CSV is treated as the primary raw experimental record:

    cec2014/raw/ablation_cec2014_run_summary_revision.csv

This file is append-only during the active experiment. It is never overwritten by
this script. Derived function-level summaries are written separately to the
processed-data directory by the frozen summary routine.

Benchmark error definition
--------------------------
For every run:

    error = best_f - f_opt

where f_opt is the declared CEC2014 global optimum for the corresponding
benchmark function.

A materially negative benchmark error (< -1e-8) is treated as a pipeline failure.
Only negligible floating-point round-off within tolerance is accepted by the
frozen validation routine.

FE-budget interpretation
------------------------
FE_budget_max is the common maximum objective-function-evaluation allowance.
The realized fe_used value is stored explicitly for every run and must satisfy:

    1 <= fe_used <= FE_budget_max

The wrapper does not reinterpret FE usage or convert it into wall-clock cost.

Reproducibility and provenance
------------------------------
This script is designed for transparent use by co-authors, reviewers, or other
researchers. The scientific results remain attributable to the frozen DMGSO
implementation; this wrapper only provides data-integrity and recovery logic.

Any future modification to the scientific implementation should trigger a new
code version, new provenance hash, and a new experimental run rather than silent
reuse of an existing raw-data file.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Set, Tuple

import numpy as np
import pandas as pd


# =============================================================================
# 1. PROJECT PATHS AND FROZEN IMPORTS
# =============================================================================

# This script is expected to reside in:
# Revision/cec2014/code/run_ablation_dmgso_cec2014_safe.py
#
# All project paths are resolved relative to the script itself so that the
# workflow does not depend on the user's current working directory.
CODE_DIR = Path(__file__).resolve().parent
CEC_DIR = CODE_DIR.parent
RAW_DIR = CEC_DIR / "raw"
PROCESSED_DIR = CEC_DIR / "processed"
BACKUP_DIR = RAW_DIR / "backups"

# Primary run-level raw dataset. During the active experiment this file is
# strictly append-only.
RUN_SUMMARY = RAW_DIR / "ablation_cec2014_run_summary_revision.csv"

# Ensure that the local revision code takes precedence over unrelated Python
# packages or legacy project files.
sys.path.insert(0, str(CODE_DIR))

# Import the already-frozen scientific implementation.
#
# The wrapper deliberately does not duplicate optimizer logic. This reduces the
# risk that recovery code accidentally diverges from the implementation used in
# the validated pilot experiment.
from run_ablation_dmgso_cec2014_revision import (  # noqa: E402
    VERSION_DESCRIPTIONS,
    append_csv,
    run_single_version,
    summarize_ablation,
    validate_result,
)
from wrapper_cec2014_revision import get_cec2014_problem  # noqa: E402


# =============================================================================
# 2. FROZEN EXPERIMENTAL PROTOCOL
# =============================================================================

# The ordering below reproduces the paired structure of the frozen ablation:
# function -> deterministic configuration -> algorithmic version.
VERSIONS = ["V0", "V1", "V2", "V3", "V4"]
FUNCTIONS = list(range(1, 31))
DIMENSION = 30
RUNS = 10
BUDGET = 300_000

# A completed experimental record is uniquely identified by these four fields.
# The key reflects the statistical pairing structure and prevents accidental
# duplication after interrupted execution.
KEY_COLUMNS = ["version", "function_id", "dimension", "run_id"]

# The expected schema mirrors the row structure generated by the frozen runner.
# Existing raw data must match this schema before they are trusted for resume.
REQUIRED_COLUMNS = [
    "suite",
    "version",
    "version_description",
    "function_id",
    "function_name",
    "category",
    "dimension",
    "run_id",
    "configuration_type",
    "FE_budget_max",
    "fe_used",
    "best_f",
    "f_opt",
    "error",
    "n_accept",
    "n_reloc",
    "wall_time_sec",
    "status",
]


# =============================================================================
# 3. EXPERIMENTAL-KEY CONSTRUCTION
# =============================================================================

def expected_keys() -> List[Tuple[str, int, int, int]]:
    """
    Construct the complete ordered set of expected experimental records.

    Returns
    -------
    list of tuple
        Tuples have the form:
        (version, function_id, dimension, run_id)

    Notes
    -----
    The ordering is intentionally matched to the frozen ablation runner:

        function -> run_id -> version

    This means that, for each benchmark function and deterministic
    configuration, V0-V4 are executed consecutively. The ordering itself is not
    part of the optimizer, but preserving it simplifies provenance and makes a
    resumed run directly comparable with an uninterrupted run.
    """
    keys: List[Tuple[str, int, int, int]] = []

    for fid in FUNCTIONS:
        for run_id in range(RUNS):
            for version in VERSIONS:
                keys.append((version, fid, DIMENSION, run_id))

    return keys


def key_set(df: pd.DataFrame) -> Set[Tuple[str, int, int, int]]:
    """
    Convert existing run-level records into their unique experimental keys.

    This representation is used only for integrity checks and skip/resume logic;
    it does not modify the stored raw data.
    """
    return {
        (
            str(row.version),
            int(row.function_id),
            int(row.dimension),
            int(row.run_id),
        )
        for row in df[KEY_COLUMNS].itertuples(index=False)
    }


# =============================================================================
# 4. EXISTING-DATA INTEGRITY AUDIT
# =============================================================================

def validate_existing(path: Path) -> pd.DataFrame:
    """
    Validate an existing ablation CSV before any resume operation.

    Parameters
    ----------
    path : pathlib.Path
        Path to the primary run-level raw CSV.

    Returns
    -------
    pandas.DataFrame
        Validated existing data. If the file does not yet exist, an empty
        DataFrame with the expected schema is returned.

    Raises
    ------
    RuntimeError
        If the file contains schema mismatches, duplicate experimental records,
        protocol mismatches, non-finite numerical values, invalid FE counts, or
        inconsistent benchmark errors.

    Scientific rationale
    --------------------
    Resume logic is useful only if the existing partial dataset is trustworthy.
    Therefore, continuation is forbidden whenever a completed record violates
    the frozen protocol. This is deliberately conservative: corrupt or ambiguous
    rows should be investigated rather than silently reused.
    """

    # Absence of the file is a valid state for a new full experiment.
    if not path.exists():
        return pd.DataFrame(columns=REQUIRED_COLUMNS)

    df = pd.read_csv(path)

    # An empty file is treated as a zero-progress experiment rather than as
    # evidence of completed optimization work.
    if df.empty:
        return pd.DataFrame(columns=REQUIRED_COLUMNS)

    # -------------------------------------------------------------------------
    # 4.1 Schema validation
    # -------------------------------------------------------------------------
    missing_columns = [c for c in REQUIRED_COLUMNS if c not in df.columns]

    if missing_columns:
        raise RuntimeError(
            "Existing CSV schema does not match the frozen ablation protocol.\n"
            f"Missing columns: {missing_columns}"
        )

    # -------------------------------------------------------------------------
    # 4.2 Uniqueness validation
    # -------------------------------------------------------------------------
    duplicates = df.duplicated(KEY_COLUMNS, keep=False)

    if duplicates.any():
        raise RuntimeError(
            "Duplicate ablation records detected. Resume is blocked to avoid "
            "ambiguous scientific records:\n"
            + df.loc[duplicates, KEY_COLUMNS].to_string(index=False)
        )

    # -------------------------------------------------------------------------
    # 4.3 Frozen-protocol validation
    # -------------------------------------------------------------------------
    versions_found = set(df["version"].astype(str).unique())

    if not versions_found.issubset(set(VERSIONS)):
        raise RuntimeError(
            f"Unexpected ablation version(s): "
            f"{sorted(versions_found - set(VERSIONS))}"
        )

    functions_found = set(
        pd.to_numeric(df["function_id"], errors="raise").astype(int).unique()
    )

    if not functions_found.issubset(set(FUNCTIONS)):
        raise RuntimeError(
            f"Unexpected CEC2014 function_id(s): "
            f"{sorted(functions_found - set(FUNCTIONS))}"
        )

    dimensions_found = set(
        pd.to_numeric(df["dimension"], errors="raise").astype(int).unique()
    )

    if dimensions_found != {DIMENSION}:
        raise RuntimeError(
            f"Dimension mismatch. Expected only D={DIMENSION}; "
            f"found {sorted(dimensions_found)}."
        )

    run_ids_found = set(
        pd.to_numeric(df["run_id"], errors="raise").astype(int).unique()
    )

    if not run_ids_found.issubset(set(range(RUNS))):
        raise RuntimeError(
            f"Unexpected run_id(s): "
            f"{sorted(run_ids_found - set(range(RUNS)))}"
        )

    budgets_found = set(
        pd.to_numeric(df["FE_budget_max"], errors="raise").astype(int).unique()
    )

    if budgets_found != {BUDGET}:
        raise RuntimeError(
            f"FE-budget mismatch. Expected only {BUDGET}; "
            f"found {sorted(budgets_found)}."
        )

    if not (df["suite"].astype(str) == "CEC2014").all():
        raise RuntimeError(
            "Unexpected benchmark-suite label found in existing raw data."
        )

    if not (
        df["configuration_type"].astype(str) == "deterministic"
    ).all():
        raise RuntimeError(
            "Unexpected configuration_type found. "
            "This ablation is defined only for deterministic configurations."
        )

    if not (
        df["status"].astype(str).str.lower() == "ok"
    ).all():
        bad = df.loc[
            df["status"].astype(str).str.lower() != "ok",
            KEY_COLUMNS + ["status"],
        ]

        raise RuntimeError(
            "One or more existing records have non-ok status:\n"
            + bad.to_string(index=False)
        )

    # -------------------------------------------------------------------------
    # 4.4 Numerical and FE integrity
    # -------------------------------------------------------------------------
    fe_used = pd.to_numeric(df["fe_used"], errors="coerce")
    best_f = pd.to_numeric(df["best_f"], errors="coerce")
    f_opt = pd.to_numeric(df["f_opt"], errors="coerce")
    error = pd.to_numeric(df["error"], errors="coerce")

    if fe_used.isna().any():
        raise RuntimeError("NaN or non-numeric fe_used value detected.")

    if (fe_used < 1).any():
        raise RuntimeError("Invalid fe_used < 1 detected.")

    if (fe_used > BUDGET).any():
        raise RuntimeError(
            "FE-budget violation detected in existing raw data."
        )

    for name, series in (
        ("best_f", best_f),
        ("f_opt", f_opt),
        ("error", error),
    ):
        if series.isna().any():
            raise RuntimeError(
                f"NaN or non-numeric value detected in {name}."
            )

        if not np.isfinite(series.to_numpy(dtype=float)).all():
            raise RuntimeError(
                f"Non-finite value detected in {name}."
            )

    # -------------------------------------------------------------------------
    # 4.5 Benchmark-error consistency
    # -------------------------------------------------------------------------
    recomputed_error = (
        best_f.to_numpy(dtype=float)
        - f_opt.to_numpy(dtype=float)
    )
    stored_error = error.to_numpy(dtype=float)

    # The tolerance is intentionally small and only accommodates normal
    # floating-point serialization differences.
    if not np.allclose(
        stored_error,
        recomputed_error,
        rtol=1e-10,
        atol=1e-8,
    ):
        raise RuntimeError(
            "Stored error is inconsistent with best_f - f_opt."
        )

    # A materially negative error would contradict the declared benchmark
    # optimum and is therefore treated as a pipeline failure rather than being
    # clipped or silently repaired.
    if (recomputed_error < -1e-8).any():
        raise RuntimeError(
            "Materially negative CEC2014 benchmark error detected."
        )

    return df


# =============================================================================
# 5. HUMAN-READABLE PROGRESS AUDIT
# =============================================================================

def print_status(
    df: pd.DataFrame,
    missing: List[Tuple[str, int, int, int]],
) -> None:
    """
    Print a compact audit summary before any computation begins.

    This output is designed to make accidental reruns obvious. In particular,
    the researcher can verify the number and identity of missing records before
    explicitly enabling execution.
    """
    total = len(expected_keys())
    existing = len(df)

    print("=" * 72)
    print("CEC2014 ABLATION SAFE-RUN AUDIT")
    print("=" * 72)
    print(f"CSV:            {RUN_SUMMARY}")
    print(f"Existing rows:  {existing}")
    print(f"Expected final: {total}")
    print(f"Missing rows:   {len(missing)}")
    print(
        f"Completion:     "
        f"{100.0 * existing / total if total else 0.0:.2f}%"
    )

    if missing:
        first = missing[0]
        last = missing[-1]

        print(
            "First missing:  "
            f"F{first[1]:02d} / "
            f"run_id={first[3]:02d} / "
            f"{first[0]}"
        )
        print(
            "Last missing:   "
            f"F{last[1]:02d} / "
            f"run_id={last[3]:02d} / "
            f"{last[0]}"
        )
    else:
        print("Dataset already complete.")

    print("=" * 72)


# =============================================================================
# 6. PROVENANCE BACKUP
# =============================================================================

def backup_existing(path: Path) -> Path | None:
    """
    Create a timestamped byte-for-byte backup of an existing active CSV.

    Notes
    -----
    A backup is created only when an active raw-data file already exists.
    The backup is never used as a scientific input automatically; it is a
    provenance and recovery artifact.

    For a brand-new run no backup is necessary because there are no prior
    completed records to preserve.
    """
    if not path.exists():
        return None

    BACKUP_DIR.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    backup_path = (
        BACKUP_DIR
        / f"{path.stem}_pre_safe_run_{timestamp}{path.suffix}"
    )

    if backup_path.exists():
        raise FileExistsError(
            f"Refusing to overwrite existing backup: {backup_path}"
        )

    shutil.copy2(path, backup_path)

    return backup_path


# =============================================================================
# 7. EXECUTION OF ONE MISSING EXPERIMENTAL RECORD
# =============================================================================

def run_one(
    version: str,
    fid: int,
    run_id: int,
) -> dict:
    """
    Execute one missing deterministic ablation configuration.

    Parameters
    ----------
    version : str
        One of V0-V4.
    fid : int
        CEC2014 function identifier.
    run_id : int
        Deterministic configuration index, 0-9.

    Returns
    -------
    dict
        One validated run-level result row with the exact schema used by the
        frozen ablation runner.

    Scientific rationale
    --------------------
    This function intentionally delegates optimization and result validation to
    the frozen implementation. The safety wrapper therefore cannot silently
    alter the optimizer or benchmark logic.
    """

    problem = get_cec2014_problem(
        function_id=fid,
        dimension=DIMENSION,
    )

    result, wall_time = run_single_version(
        problem=problem,
        version=version,
        dimension=DIMENSION,
        budget=BUDGET,
        run_id=run_id,
        trace=False,
        trace_every=20,
    )

    best_f = float(result.best_f)
    fe_used = int(result.fe_used)
    n_accept = int(getattr(result, "n_accept", 0))
    n_reloc = int(getattr(result, "n_reloc", 0))
    f_opt = float(problem.optimum)

    # Use the frozen benchmark-integrity routine rather than reproducing its
    # logic independently.
    error = validate_result(
        version=version,
        fid=fid,
        run_id=run_id,
        best_f=best_f,
        f_opt=f_opt,
        fe_used=fe_used,
        budget=BUDGET,
    )

    return {
        "suite": "CEC2014",
        "version": version,
        "version_description": VERSION_DESCRIPTIONS[version],
        "function_id": fid,
        "function_name": problem.name,
        "category": problem.category,
        "dimension": DIMENSION,
        "run_id": run_id,
        "configuration_type": "deterministic",
        "FE_budget_max": BUDGET,
        "fe_used": fe_used,
        "best_f": best_f,
        "f_opt": f_opt,
        "error": error,
        "n_accept": n_accept,
        "n_reloc": n_reloc,
        "wall_time_sec": float(wall_time),
        "status": "ok",
    }


# =============================================================================
# 8. FINAL COMPLETENESS AND INTEGRITY AUDIT
# =============================================================================

def final_audit() -> None:
    """
    Require a complete and internally valid 1,500-row ablation dataset.

    The experiment is considered complete only if every expected
    (function, run_id, version) combination is present exactly once.
    """
    df = validate_existing(RUN_SUMMARY)

    expected = expected_keys()
    completed = key_set(df)

    missing = [
        key
        for key in expected
        if key not in completed
    ]

    if len(df) != len(expected):
        raise RuntimeError(
            f"Final row-count mismatch: "
            f"{len(df)} != {len(expected)}"
        )

    if missing:
        raise RuntimeError(
            f"Final dataset still contains "
            f"{len(missing)} missing records. "
            f"First missing key: {missing[0]}"
        )

    print()
    print("[PASS] FINAL ABLATION AUDIT")
    print(
        f"[PASS] Unique complete rows: "
        f"{len(df)} / {len(expected)}"
    )
    print("[PASS] No duplicates")
    print("[PASS] All status=ok")
    print("[PASS] FE budgets valid")
    print(
        "[PASS] Errors finite and non-negative "
        "within benchmark tolerance"
    )

    # Function-level descriptive summaries are derived only after the complete
    # run-level dataset has passed the integrity audit.
    summarize_ablation(RUN_SUMMARY)


# =============================================================================
# 9. COMMAND-LINE INTERFACE
# =============================================================================

def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.

    Safety policy
    -------------
    Dry-run is the default mode. The --execute flag is deliberately explicit so
    that opening or inspecting the script cannot accidentally start a long
    experiment.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Crash-safe and restart-safe CEC2014 DMGSO ablation runner "
            "for the Information Sciences revision."
        )
    )

    parser.add_argument(
        "--execute",
        action="store_true",
        help=(
            "Compute and append only missing records. "
            "Without this flag, the script performs a read-only audit."
        ),
    )

    return parser.parse_args()


# =============================================================================
# 10. MAIN SAFE-RUN WORKFLOW
# =============================================================================

def main() -> None:
    """
    Execute the safe-run workflow.

    Workflow
    --------
    1. Audit existing raw data.
    2. Compare completed keys with the frozen 1,500-record protocol.
    3. Print missing-record status.
    4. Stop in dry-run mode unless --execute is provided.
    5. Create a provenance backup when continuing an existing partial file.
    6. Execute only missing configurations.
    7. Append each validated result immediately.
    8. Perform a final completeness audit and write derived summaries.
    """
    args = parse_args()

    # -------------------------------------------------------------------------
    # 10.1 Read-only pre-execution audit
    # -------------------------------------------------------------------------
    df = validate_existing(RUN_SUMMARY)

    expected = expected_keys()
    completed = key_set(df)
    expected_set = set(expected)

    # Existing records that do not belong to the frozen protocol indicate that
    # the active CSV was created under a different experiment definition.
    unexpected = completed - expected_set

    if unexpected:
        raise RuntimeError(
            "Existing CSV contains records outside the frozen protocol. "
            f"Examples: {sorted(unexpected)[:10]}"
        )

    missing = [
        key
        for key in expected
        if key not in completed
    ]

    print_status(df, missing)

    # -------------------------------------------------------------------------
    # 10.2 Already-complete dataset
    # -------------------------------------------------------------------------
    if not missing:
        print("[INFO] No optimization records are missing.")
        final_audit()
        return

    # -------------------------------------------------------------------------
    # 10.3 Default safety mode: read-only
    # -------------------------------------------------------------------------
    if not args.execute:
        print("[DRY-RUN] No file was modified.")
        print(
            "[DRY-RUN] Rerun with --execute to append "
            "only the missing records."
        )
        return

    # -------------------------------------------------------------------------
    # 10.4 Provenance backup before continuing an existing partial run
    # -------------------------------------------------------------------------
    backup_path = backup_existing(RUN_SUMMARY)

    if backup_path is not None:
        print(f"[BACKUP] {backup_path}")
    else:
        print(
            "[BACKUP] No active CSV existed; "
            "starting a new append-only dataset."
        )

    print(
        f"[EXECUTE] Computing {len(missing)} "
        "missing experimental records..."
    )

    # Re-read immediately before computation in case the active file changed
    # between the initial audit and execution.
    current_df = validate_existing(RUN_SUMMARY)
    completed_now = key_set(current_df)

    # -------------------------------------------------------------------------
    # 10.5 Crash-safe append loop
    # -------------------------------------------------------------------------
    for version, fid, dimension, run_id in expected:

        key = (
            version,
            fid,
            dimension,
            run_id,
        )

        # Completed records are never recomputed or rewritten.
        if key in completed_now:
            continue

        row = run_one(
            version=version,
            fid=fid,
            run_id=run_id,
        )

        # Last-moment protection against duplicate append in case the active CSV
        # was modified externally while this process was running.
        if RUN_SUMMARY.exists():
            latest_df = validate_existing(RUN_SUMMARY)

            if key in key_set(latest_df):
                raise RuntimeError(
                    "Refusing duplicate append because the experimental key "
                    f"already exists: {key}"
                )

        # append_csv writes the completed result immediately. Therefore, a later
        # crash loses at most the currently running optimization, not previous
        # completed records.
        append_csv(
            row,
            RUN_SUMMARY,
        )

        completed_now.add(key)

        print(
            f"[OK] {version:2s} | "
            f"F{fid:02d} | "
            f"D={DIMENSION} | "
            f"run_id={run_id:02d} | "
            f"error={float(row['error']):.6e} | "
            f"FE={int(row['fe_used'])}/{BUDGET} | "
            f"accept={int(row['n_accept'])} | "
            f"reloc={int(row['n_reloc'])}"
        )

    # -------------------------------------------------------------------------
    # 10.6 Final scientific-data audit
    # -------------------------------------------------------------------------
    final_audit()

    print()
    print(
        "CEC2014 crash-safe ablation run "
        "finished successfully."
    )


if __name__ == "__main__":
    main()
